create table category_tbl(
	id int generated by default as identity,
	name varchar(25) not null unique,
	primary kay(id)
);

create table product_tbl(
	id int generated by default as identity,
	name varchar(35) not null,
	category_id id not null,
	primary key(id),
	constraint fk_product_to_category foreign key (category_id) references category_tbl(id)
);